# Generated by Django 4.2.9 on 2024-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_perishableitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perishableitem',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='perishableitem',
            name='estimated_expiration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
